### ISSUE TITLE
this is missing the /static folder

### ISSUE THREAD

**Issue by rbuckland** [ahmadrosid/rust-react-chat#1]

**Comment by ndcuenco** [comment]
have you created the index.html file inside the static folder?

![image](https://github.com/ahmadrosid/rust-react-chat/assets/100282148/ca0a729a-f917-443e-be64-aaae60cd11b4)
 
I have this error after running index page is blank as shown below

![image](https://github.com/ahmadrosid/rust-react-chat/assets/100282148/5709fa7c-eb6c-40eb-9219-d6efc972f378)
